{{ Html::script('js/main.js') }}
{{ Html::script(mix('js/app.js')) }}
{{ Html::script('control/js/jquery/jquery_ui/jquery-ui.min.js') }}
{{ Html::script('control/js/plugins/highcharts/highcharts.js') }}
{{ Html::script('control/js/plugins/c3charts/d3.min.js') }}
{{ Html::script('control/js/plugins/c3charts/c3.min.js') }}
{{ Html::script('control/js/plugins/circles/circles.js') }}
{{ Html::script('control/js/plugins/jvectormap/jquery.jvectormap.min.js') }}
{{ Html::script('control/js/plugins/jvectormap/assets/jquery-jvectormap-us-lcc-en.js') }}
{{ Html::script('control/js/plugins/fullcalendar/lib/moment.min.js') }}
{{ Html::script('control/js/plugins/fullcalendar/fullcalendar.min.js') }}
{{ Html::script('control/allcp/forms/js/jquery-ui-monthpicker.min.js') }}
{{ Html::script('control/allcp/forms/js/jquery-ui-datepicker.min.js') }}
{{ Html::script('control/js/plugins/magnific/jquery.magnific-popup.js') }}
{{ Html::script('control/js/utility/utility.js') }}
{{ Html::script('control/js/utility/malihu-custom-scrollbar-plugin-master/jquery.mCustomScrollbar.concat.min.js') }}
{{ Html::script('control/js/demo/demo.js') }}
{{ Html::script('control/js/main.js') }}
{{ Html::script('control/js/demo/widgets.js') }}
{{ Html::script('control/js/demo/widgets_sidebar.js') }}
{{ Html::script('control/js/pages/dashboard1.js') }}
